"""initial schema

Revision ID: b9a904907743
Revises:
Create Date: 2026-07-27 08:40:51.442326

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b9a904907743'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'broadcasts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('content_chat_id', sa.BigInteger(), nullable=False),
        sa.Column('content_message_id', sa.BigInteger(), nullable=False),
        sa.Column('status', sa.String(length=8), nullable=False),
        sa.Column('last_user_id', sa.BigInteger(), nullable=True),
        sa.Column('sent', sa.Integer(), server_default='0', nullable=False),
        sa.Column('failed', sa.Integer(), server_default='0', nullable=False),
        sa.Column('blocked', sa.Integer(), server_default='0', nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'running', 'done', 'canceled')",
            name=op.f('ck_broadcasts_status_valid'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_broadcasts')),
    )
    op.create_table(
        'job_heartbeats',
        sa.Column('job_name', sa.String(length=64), nullable=False),
        sa.Column(
            'last_success_at', sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column('last_error', sa.Text(), nullable=True),
        sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('job_name', name=op.f('pk_job_heartbeats')),
    )
    op.create_table(
        'tariffs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=16), nullable=False),
        sa.Column('title_ru', sa.String(length=64), nullable=False),
        sa.Column('duration_days', sa.Integer(), nullable=False),
        sa.Column('price_kopeks', sa.Integer(), nullable=False),
        sa.Column(
            'sort_order', sa.Integer(), server_default='0', nullable=False
        ),
        sa.Column(
            'is_active', sa.Boolean(), server_default='true', nullable=False
        ),
        sa.Column(
            'is_archived', sa.Boolean(), server_default='false', nullable=False
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_tariffs')),
        sa.UniqueConstraint('code', name=op.f('uq_tariffs_code')),
    )
    op.create_index(
        'ix_tariffs_active_order',
        'tariffs',
        ['is_active', 'sort_order'],
        unique=False,
    )
    op.create_table(
        'users',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('username', sa.String(length=64), nullable=True),
        sa.Column('first_name', sa.String(length=128), nullable=True),
        sa.Column(
            'is_bot_blocked',
            sa.Boolean(),
            server_default='false',
            nullable=False,
        ),
        sa.Column('trial_used_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'support_blocked_at', sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    )
    op.create_table(
        'payments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('tariff_id', sa.Integer(), nullable=False),
        sa.Column('provider', sa.String(length=9), nullable=False),
        sa.Column('status', sa.String(length=11), nullable=False),
        sa.Column('amount_kopeks', sa.Integer(), nullable=False),
        sa.Column('paid_amount_kopeks', sa.Integer(), nullable=True),
        sa.Column('paid_currency', sa.String(length=8), nullable=True),
        sa.Column('provider_invoice_id', sa.String(length=128), nullable=True),
        sa.Column(
            'target_expires_at', sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column('invoice_url', sa.Text(), nullable=True),
        sa.Column(
            'invoice_expires_at', sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('provisioned_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider IN ('yoomoney', 'cryptobot')",
            name=op.f('ck_payments_provider_valid'),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'paid', 'provisioned', 'expired', 'canceled')",
            name=op.f('ck_payments_status_valid'),
        ),
        sa.ForeignKeyConstraint(
            ['tariff_id'], ['tariffs.id'], name=op.f('fk_payments_tariff_id')
        ),
        sa.ForeignKeyConstraint(
            ['user_id'], ['users.id'], name=op.f('fk_payments_user_id')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
        sa.UniqueConstraint(
            'provider',
            'provider_invoice_id',
            name='uq_payments_provider_invoice_id',
        ),
    )
    op.create_index('ix_payments_status', 'payments', ['status'], unique=False)
    op.create_index(
        'ix_payments_user_id_created_at',
        'payments',
        ['user_id', 'created_at'],
        unique=False,
    )
    op.create_table(
        'subscriptions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('status', sa.String(length=7), nullable=False),
        sa.Column('origin', sa.String(length=11), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('panel_user_id', sa.String(length=32), nullable=False),
        sa.Column('subscription_token', sa.String(length=64), nullable=True),
        sa.Column('provisioned_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('notified_stage', sa.String(length=4), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.CheckConstraint(
            "origin IN ('trial', 'purchase', 'admin_grant')",
            name=op.f('ck_subscriptions_origin_valid'),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'active', 'expired', 'revoked')",
            name=op.f('ck_subscriptions_status_valid'),
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
            name=op.f('fk_subscriptions_user_id'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
        sa.UniqueConstraint('user_id', name=op.f('uq_subscriptions_user_id')),
    )
    op.create_index(
        'ix_subscriptions_status_expires_at',
        'subscriptions',
        ['status', 'expires_at'],
        unique=False,
    )
    op.create_table(
        'support_messages',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('admin_chat_id', sa.BigInteger(), nullable=False),
        sa.Column('admin_message_id', sa.BigInteger(), nullable=False),
        sa.Column('direction', sa.String(length=3), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.CheckConstraint(
            "direction IN ('in', 'out')",
            name=op.f('ck_support_messages_direction_valid'),
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
            name=op.f('fk_support_messages_user_id'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_support_messages')),
        sa.UniqueConstraint(
            'admin_chat_id',
            'admin_message_id',
            name='uq_support_messages_admin_chat_id_admin_message_id',
        ),
    )
    op.create_index(
        'ix_support_messages_user_id',
        'support_messages',
        ['user_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_support_messages_user_id', table_name='support_messages')
    op.drop_table('support_messages')
    op.drop_index(
        'ix_subscriptions_status_expires_at', table_name='subscriptions'
    )
    op.drop_table('subscriptions')
    op.drop_index('ix_payments_user_id_created_at', table_name='payments')
    op.drop_index('ix_payments_status', table_name='payments')
    op.drop_table('payments')
    op.drop_table('users')
    op.drop_index('ix_tariffs_active_order', table_name='tariffs')
    op.drop_table('tariffs')
    op.drop_table('job_heartbeats')
    op.drop_table('broadcasts')
    # ### end Alembic commands ###
