"""payment days applied latch

Revision ID: dc026fb20f91
Revises: 9f9809a15a9c
Create Date: 2026-07-28 11:53:09.802787

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dc026fb20f91'
down_revision: str | Sequence[str] | None = '9f9809a15a9c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'payments',
        sa.Column(
            'days_applied_at', sa.DateTime(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'days_applied_at')
    # ### end Alembic commands ###
